draw_self();
var char = string_char_at(global.letter, 1);
var room_w = room_width;
var room_h = room_height;
var center_x = room_w / 2;
var center_y = room_h / 2;
var original_font = draw_get_font();
draw_set_font(fntLetter);
draw_text(center_x, center_y, char);
draw_set_font(original_font);